name = "nanami-guestbook-cleaner"
main = "src/index.ts"
compatibility_date = "2026-07-17"
workers_dev = false

[triggers]
crons = ["*/15 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "nanami-guestbook"
database_id = "f5e228bb-8bfa-43e6-980c-70bdf4d1dbd0"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "nanami-guestbook-photos"
